// app/layout.js (หรือชื่อไฟล์ RootLayout ของคุณ)
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Geist, Geist_Mono } from "next/font/google";
import Navigation from "./component/Navigation";
import Footer from './component/Footer';
import './globals.css'; // Your global styles
import { Poppins } from 'next/font/google';
import { Inter, Kanit } from 'next/font/google';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* เพิ่ม Font Awesome CDN ตรงนี้ */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" // ใช้เวอร์ชันล่าสุดเท่าที่เป็นไปได้
          integrity="sha512-..." // สำคัญ: ควรแทนที่ด้วย integrity hash ที่ถูกต้องของเวอร์ชันที่คุณใช้
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>
        <div className='container-fluid'>
          <div className='row'>
            <div className='col-12'>
            </div>
          </div>
        <Navigation />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}


